create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'user' check (role in ('user', 'admin'))
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  price numeric(10,2) not null check (price >= 0),
  image_url text not null,
  category text not null check (category in ('Hoodie', 'Shirt', 'Short')),
  sizes text[] not null default array['XS','S','M','L','XL']::text[] check (sizes <@ array['XS','S','M','L','XL']::text[]),
  colors text[] not null default array[]::text[],
  color_images jsonb not null default '{}'::jsonb,
  stock integer not null default 0 check (stock >= 0),
  is_featured boolean not null default false
);

alter table public.products add column if not exists description text not null default '';
alter table public.products add column if not exists sizes text[] not null default array['XS','S','M','L','XL']::text[];
alter table public.products add column if not exists colors text[] not null default array[]::text[];
alter table public.products add column if not exists color_images jsonb not null default '{}'::jsonb;
alter table public.products add column if not exists is_featured boolean not null default false;

alter table public.products drop constraint if exists products_category_check;
alter table public.products
add constraint products_category_check check (category in ('Hoodie', 'Shirt', 'Short'));

alter table public.products drop constraint if exists products_sizes_check;

update public.products
set sizes = (
  select coalesce(array_agg(mapped_size), array['XS','S','M','L','XL']::text[])
  from (
    select case
      when lower(trim(size_value)) = 'xs' then 'XS'
      when lower(trim(size_value)) = 's' then 'S'
      when lower(trim(size_value)) = 'm' then 'M'
      when lower(trim(size_value)) = 'l' then 'L'
      when lower(trim(size_value)) = 'xl' then 'XL'
      else null
    end as mapped_size
    from unnest(coalesce(public.products.sizes, array[]::text[])) as size_value
  ) normalized
  where mapped_size is not null
);

alter table public.products
add constraint products_sizes_check check (sizes <@ array['XS','S','M','L','XL']::text[]);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  total_price numeric(10,2) not null check (total_price >= 0),
  status text not null default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered')),
  shipping_details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.orders alter column shipping_details set default '{}'::jsonb;
update public.orders set shipping_details = '{}'::jsonb where shipping_details is null;
alter table public.orders alter column shipping_details set not null;

alter table public.orders drop constraint if exists orders_shipping_details_check;
alter table public.orders
add constraint orders_shipping_details_check check (
  jsonb_typeof(shipping_details) = 'object'
  and shipping_details ? 'fullName'
  and shipping_details ? 'address'
  and shipping_details ? 'contactNumber'
  and shipping_details ? 'paymentMethod'
  and coalesce(btrim(shipping_details ->> 'fullName'), '') <> ''
  and coalesce(btrim(shipping_details ->> 'address'), '') <> ''
  and coalesce(btrim(shipping_details ->> 'contactNumber'), '') <> ''
  and lower(coalesce(shipping_details ->> 'paymentMethod', '')) = 'cod'
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  size text,
  color text,
  quantity integer not null check (quantity > 0),
  price numeric(10,2) not null check (price >= 0)
);

alter table public.order_items add column if not exists size text;
alter table public.order_items add column if not exists color text;

create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  unique (user_id, product_id)
);

create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reviewer_name text not null default 'Customer',
  rating integer not null check (rating between 1 and 5),
  title text not null default '',
  comment text not null default '',
  created_at timestamptz not null default now(),
  unique (product_id, user_id)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, role)
  values (new.id, new.raw_user_meta_data ->> 'full_name', new.email, 'user')
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.wishlist enable row level security;
alter table public.product_reviews enable row level security;

create policy "profiles_select_own" on public.profiles
for select using (auth.uid() = id);

create policy "profiles_insert_own" on public.profiles
for insert with check (auth.uid() = id);

create policy "profiles_update_own" on public.profiles
for update using (auth.uid() = id);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

create or replace function public.adjust_product_stock(p_product_id bigint, p_delta integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_stock integer;
  updated_stock integer;
begin
  if auth.uid() is null then
    raise exception 'Unauthorized';
  end if;

  select stock
  into current_stock
  from public.products
  where id = p_product_id
  for update;

  if current_stock is null then
    raise exception 'Product not found';
  end if;

  updated_stock := current_stock + p_delta;

  if updated_stock < 0 then
    raise exception 'Not enough stock available for this product';
  end if;

  update public.products
  set stock = updated_stock
  where id = p_product_id;

  return updated_stock;
end;
$$;

revoke all on function public.adjust_product_stock(bigint, integer) from public;
grant execute on function public.adjust_product_stock(bigint, integer) to authenticated;

create policy "products_public_read" on public.products
for select using (true);

create policy "products_admin_all" on public.products
for all using (public.is_admin()) with check (public.is_admin());

create policy "wishlist_select_own" on public.wishlist
for select using (auth.uid() = user_id);

create policy "wishlist_insert_own" on public.wishlist
for insert with check (auth.uid() = user_id);

create policy "wishlist_delete_own" on public.wishlist
for delete using (auth.uid() = user_id);

create policy "product_reviews_public_read" on public.product_reviews
for select using (true);

create policy "product_reviews_insert_own" on public.product_reviews
for insert with check (auth.uid() = user_id);

create policy "product_reviews_update_own" on public.product_reviews
for update using (auth.uid() = user_id);

create policy "product_reviews_delete_own" on public.product_reviews
for delete using (auth.uid() = user_id);

create policy "product_reviews_admin_all" on public.product_reviews
for all using (public.is_admin()) with check (public.is_admin());

create policy "orders_select_own" on public.orders
for select using (auth.uid() = user_id);

create policy "orders_insert_own" on public.orders
for insert with check (auth.uid() = user_id);

create policy "orders_admin_all" on public.orders
for all using (public.is_admin()) with check (public.is_admin());

create policy "order_items_select_via_order" on public.order_items
for select using (
  exists (
    select 1 from public.orders
    where public.orders.id = order_items.order_id
      and public.orders.user_id = auth.uid()
  )
);

create policy "order_items_insert_via_order" on public.order_items
for insert with check (
  exists (
    select 1 from public.orders
    where public.orders.id = order_items.order_id
      and public.orders.user_id = auth.uid()
  )
);

create policy "order_items_admin_all" on public.order_items
for all using (public.is_admin()) with check (public.is_admin());

create policy "profiles_admin_read" on public.profiles
for select using (public.is_admin());

create policy "profiles_admin_update" on public.profiles
for update using (public.is_admin()) with check (public.is_admin());

create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_products_category on public.products(category);
create index if not exists idx_products_is_featured on public.products(is_featured);
create index if not exists idx_products_search on public.products using gin(to_tsvector('english', name || ' ' || description));
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_order_items_product_id on public.order_items(product_id);
create index if not exists idx_product_reviews_product_id on public.product_reviews(product_id);
